service: twilio-services

package:
  individually: true
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    ACCOUNT_SID: ${file(./config.yml):ACCOUNT_SID}
    ACCOUNT_TOKEN: ${file(./config.yml):ACCOUNT_TOKEN}
    FROM_NUMBER: ${file(./config.yml):FROM_NUMBER}

functions:
  send-message:
    handler: send-message/index.send
    package:
      include:
        - node_modules/**
    events:
      - http:
          path: message/send
          method: post
          cors: true

plugins:
  - serverless-plugin-optimize